apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-deploy
  name: hello-world-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-deploy
    spec:
      containers:
        - image: gcr.io/google-samples/hello-app:1.0
          name: hello-app
