apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-myql-data
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: c1-nfs1
    path: "/export/volumes/mysql"
