apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-deploy
  name: hello-world-deploy
  namespace: default
spec:
  clusterIP: 10.97.122.74
  clusterIPs:
    - 10.97.122.74
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-world-deploy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
