apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  accessModes:
   - ReadWriteMany
  mountOptions:
   - nfsvers=4.1
  capacity:
     storage: 30Gi
  nfs:
    server: c1-nfs1
    path: "/export/volumes/mysql"
